### ISSUE TITLE
MKVirtualEnv command

### ISSUE THREAD

**Issue by bweston92** [toranb/django-bower-registry#7]
I've looked all over the place for the command. I've installed `virtalenv` but that doesn't come with `mkvirtualenv`. Any ideas?

**Comment by toranb** [comment]
ah, my fault for not being more specific here. mkvirtualenv is actually a shortcut that's on your path when virtualenvwrapper is installed

Here is the installer for OSX that I use to pull in virtualenv and virtualenv wrapper

https://github.com/toranb/osx-workstation/blob/master/installer#L47

Here is the linux installer I've used on ubuntu in the past

https://github.com/toranb/ubuntu-development-machine/blob/master/ubuntu.json#L34

(and the ruby chef recipe that does the work for the above configuration) 

https://github.com/toranb/ubuntu-development-machine/blob/master/cookbooks/development/recipes/default.rb#L15
