### ISSUE TITLE
Public repository.

### ISSUE THREAD

**Issue by bweston92** [toranb/django-bower-registry#8]
Bower only looks in the 1 repository. If I haven't defined the public repository packages in my private repository they're not found. The NodeJS version of a private-bower repository ask you also for the public repository... Maybe this is something you could do too/

https://github.com/Hacklone/private-bower

**Comment by toranb** [comment]
Ah, excellent point ! I'd like to commit a little more time at some point to pull this in! If you have any bandwidth to contribute in the near future and would like to hack on this that works also

**Comment by bweston92** [comment]
Sorry I have very little Python knowledge. The one language I've never really sat down with.
